Squisher updates

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -1,26 +1,16 @@
-#!/bin/sh
+#!/bin/bash
 #
-# Squish a CM otapackage for distribution
-# cyanogen
+# Squish a Vanir otapackage for distribution
+# credit for original version: CM
 #
 
-OUT_TARGET_HOST=`uname -a | grep Darwin`
-if [ -z "$OUT_TARGET_HOST" ]
-then
-   OUT_TARGET_HOST=linux-x86
-   MD5=md5sum
-   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
-   SED=sed
-else
-   OUT_TARGET_HOST=darwin-x86
-   MD5=md5
-   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
-   SED=gsed
-fi
+export ANDROID_BUILD_TOP=$ANDROID_BUILD_TOP
+
+. $ANDROID_BUILD_TOP/vendor/vanir/tools/functions
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-	echo "ERROR: $0 only works with a full build environment. $OUT should exist."
-	exit 1
+    echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+    exit 1
 fi
 
 if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
@@ -32,41 +22,40 @@ else
     OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
 fi
 if [ ! -f "$OTAPACKAGE" ]; then
-	echo "$OTAPACKAGE doesn't exist!";
-	exit 1
+    echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
+    exit 1
 fi
 
-OPTICHARGER=$ANDROID_BUILD_TOP/vendor/vanir/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
 # Some products want a squashfs for xbin for space
 case "$TARGET_PRODUCT" in
-	cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
-	*) WANT_SQUASHFS=0 ;;
+    cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
+    *) WANT_SQUASHFS=0 ;;
 esac
 
 if [ "$WANT_SQUASHFS" -eq 1 ]; then
-	fatal=0
-	MKSQUASHFS_VER_REQ=4
-	if type mksquashfs >/dev/null 2>&1; then
-		if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
-			echo
-			echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
-			fatal=1
-		fi
-	else
-		echo
-		echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
-		fatal=1
-	fi
+    fatal=0
+    MKSQUASHFS_VER_REQ=4
+    if type mksquashfs >/dev/null 2>&1; then
+        if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
+            echo
+            echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
+                fatal=1
+            fi
+        else
+            echo
+            echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
+            fatal=1
+        fi
 
-	if [ "$fatal" -ne 0 ]; then
-		echo
-		echo "       Unoptimized package is still available at"
-		echo "         $OTAPACKAGE"
-		exit $fatal
-	fi
+        if [ "$fatal" -ne 0 ]; then
+            echo
+            echo "       Unoptimized package is still available at"
+            echo "         $OTAPACKAGE"
+            exit $fatal
+        fi
 fi
 
 REPACK=$OUT/repack.d
@@ -81,7 +70,7 @@ mkdir $REPACK/ota
 cd $REPACK/ota
 printf "Unpacking $OTAPACKAGE..."
 unzip $QUIET $OTAPACKAGE
-cp -r $OUT/data $REPACK/ota/data
+ln -s  $OUT/data $REPACK/ota/data
 echo
 
 # Move all apks to the same directory so xargs can
@@ -89,21 +78,16 @@ echo
 # framework-res.apk in parallel with other apks
 mkdir -p $REPACK/parallel
 cd $REPACK/parallel
-cp $REPACK/ota/system/framework/framework-res.apk .
-cp $REPACK/ota/system/app/*.apk .
+ln -s $REPACK/ota/system/framework/framework-res.apk .
+for x in $REPACK/ota/system/app/*.apk; do ln -s $x .; done
 
-# Do optimization in parallel
-find ./ -name \*.apk | $XARGS $OPTICHARGER
-
-# Move optimized apks to repack directory
-mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
-mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/
+# Do optimization in parallel - NUKE WAS HERE!
+$PARALLELIZER `find ./ -name \*.apk`
 
 # Return to directory
 cd $REPACK/ota
 rm -rf $REPACK/parallel
 )
-
 
 if [ "$WANT_SQUASHFS" -eq 1 ]; then
 	squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
@@ -119,10 +103,6 @@ if [ "$WANT_SQUASHFS" -eq 1 ]; then
 	# Remove xbin stuff and fix up updater-script
 	$SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
 fi
-
-# Reduce size of beats effects by ALOT (these soundimage text files are more than 50% comments, and there ARE LOADS OF THEM)
-echo "66% of Beats' configs are comments... which are USELESS. BUH BYE BEATS COMMENTS!"
-for x in $REPACK/ota/system/etc/soundimage/*.txt; do $SED -i 's/ *\#.*//g' $x; done 
 
 # No need for recovery
 rm -rf $REPACK/ota/recovery
@@ -140,10 +120,10 @@ echo $CL_CYN"Zipping package..."$CL_RST
 echo
 echo $CL_CYN"Signing package..."$CL_RST
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
-java -Xmx1024m \
-	-jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
-	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-	$REPACK/update.zip $OUTFILE
+java -Xmx2048m \
+    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
+    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+    $REPACK/update.zip $OUTFILE
 echo
 echo $CL_CYN"Cleaning up..."$CL_RST
 rm -rf $REPACK
